//! Typed error hierarchies for the KAI runtime.
//!
//! Provides the root [`KaiError`] and specialized domain error types
//! to propagate failures across crate boundaries without stringly-typed errors.

use thiserror::Error;

/// Specialized Result type alias for KAI operations.
pub type Result<T, E = KaiError> = std::result::Result<T, E>;

/// Root error type for the KAI runtime.
#[derive(Debug, Error)]
pub enum KaiError {
    /// Failure during tool invocation, validation, or execution.
    #[error("Tool error: {0}")]
    Tool(#[from] ToolError),

    /// Failure in the deterministic context pipeline or AST processing.
    #[error("Context error: {0}")]
    Context(#[from] ContextError),

    /// Failure in session persistence, graph traversal, or state management.
    #[error("Session error: {0}")]
    Session(#[from] SessionError),

    /// Failure in multi-agent orchestration, task inbox, or dispatching.
    #[error("Orchestrator error: {0}")]
    Orchestrator(#[from] OrchestratorError),

    /// Security policy violation or boundary enforcement failure.
    #[error("Sandbox error: {0}")]
    Sandbox(#[from] SandboxError),

    /// Failure during model inference, API communication, or rate limits.
    #[error("Inference error: {0}")]
    Inference(#[from] InferenceError),

    /// Configuration parsing or environment validation failure.
    #[error("Configuration error: {0}")]
    Config(#[from] ConfigError),

    /// Failure serializing or deserializing data.
    #[error("Serialization error: {0}")]
    Serialization(#[from] serde_json::Error),

    /// Standard I/O failure.
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),

    /// Unclassified internal runtime failure with causal context.
    #[error(transparent)]
    Internal(#[from] InternalError),
}

impl From<String> for KaiError {
    fn from(msg: String) -> Self {
        Self::Internal(InternalError::new(msg))
    }
}

impl From<&str> for KaiError {
    fn from(msg: &str) -> Self {
        Self::Internal(InternalError::new(msg))
    }
}

/// Unclassified internal runtime failure with optional root cause tracking.
#[derive(Debug, Error)]
#[error("Internal runtime error: {message}")]
pub struct InternalError {
    /// Description of the internal failure.
    pub message: String,
    /// Optional underlying root cause preserving the error chain.
    #[source]
    pub source: Option<Box<dyn std::error::Error + Send + Sync>>,
}

impl InternalError {
    /// Constructs a new [`InternalError`] with a message.
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
            source: None,
        }
    }

    /// Constructs an [`InternalError`] with a message and an underlying cause.
    pub fn with_cause(
        message: impl Into<String>,
        source: impl Into<Box<dyn std::error::Error + Send + Sync>>,
    ) -> Self {
        Self {
            message: message.into(),
            source: Some(source.into()),
        }
    }
}

/// Errors occurring within tool definitions or executions.
#[derive(Debug, Error, PartialEq, Eq)]
pub enum ToolError {
    /// The requested tool does not exist in the active registry.
    #[error("Tool not found: {name}")]
    NotFound {
        /// Name of the requested tool.
        name: String,
    },

    /// The tool arguments failed schema validation.
    #[error("Invalid arguments for tool '{name}': {reason}")]
    InvalidArguments {
        /// Name of the tool.
        name: String,
        /// Description of the validation failure.
        reason: String,
    },

    /// Tool execution terminated with an error.
    #[error("Execution of tool '{name}' failed: {reason}")]
    ExecutionFailed {
        /// Name of the tool.
        name: String,
        /// Failure details reported by the execution engine.
        reason: String,
    },

    /// Output generated by the tool exceeded configured size or item caps.
    #[error(
        "Output limit exceeded for tool '{name}': {size} bytes exceeds limit of {limit} bytes"
    )]
    OutputLimitExceeded {
        /// Name of the tool.
        name: String,
        /// Size in bytes of the generated output.
        size: usize,
        /// Configured limit in bytes.
        limit: usize,
    },

    /// The tool execution exceeded its allotted timeout window.
    #[error("Execution of tool '{name}' timed out after {duration_secs} seconds")]
    Timeout {
        /// Name of the tool.
        name: String,
        /// Configured timeout duration in seconds.
        duration_secs: u64,
    },
}

/// Errors occurring within the deterministic context optimization pipeline.
#[derive(Debug, Error, PartialEq, Eq)]
pub enum ContextError {
    /// Token usage exceeded the allowed context window threshold.
    #[error("Context token limit exceeded: current {tokens}, limit {limit}")]
    TokenLimitExceeded {
        /// Number of tokens evaluated.
        tokens: usize,
        /// Maximum allowed token cap.
        limit: usize,
    },

    /// Tree-sitter parsing or syntax tree extraction failed.
    #[error("AST parsing failed for grammar '{language}': {reason}")]
    AstParsingFailed {
        /// Target programming language or grammar name.
        language: String,
        /// Error details from parser.
        reason: String,
    },

    /// Requested window boundaries were invalid or out of file range.
    #[error("Invalid window bounds: offset {offset}, limit {limit}")]
    InvalidWindow {
        /// Starting line offset requested.
        offset: usize,
        /// Number of lines requested.
        limit: usize,
    },
}

/// Errors occurring within session state and DAG memory management.
#[derive(Debug, Error, PartialEq, Eq)]
pub enum SessionError {
    /// The specified session could not be found.
    #[error("Session not found: {session_id}")]
    NotFound {
        /// Unique session identifier.
        session_id: String,
    },

    /// A node within the session DAG does not exist.
    #[error("Graph node not found: {node_id}")]
    NodeNotFound {
        /// Unique node identifier.
        node_id: String,
    },

    /// Cycle detected while manipulating the session DAG.
    #[error("Cycle detected at node {node_id}")]
    CycleDetected {
        /// Identifier of the node causing the cycle.
        node_id: String,
    },

    /// Session state data on disk is corrupted or unreadable.
    #[error("Corrupted session state: {reason}")]
    CorruptedState {
        /// Description of the corruption.
        reason: String,
    },
}

/// Errors occurring within multi-agent task dispatching and services.
#[derive(Debug, Error, PartialEq, Eq)]
pub enum OrchestratorError {
    /// An ephemeral sub-agent failed during its lifecycle.
    #[error("Sub-agent '{agent_id}' execution failed: {reason}")]
    SubAgentFailed {
        /// Identifier of the failed sub-agent.
        agent_id: String,
        /// Failure details.
        reason: String,
    },

    /// The concurrent Task Inbox receiver has been dropped or closed.
    #[error("Task inbox channel is closed")]
    TaskInboxClosed,

    /// Execution was cancelled or redirected by an external steering signal.
    #[error("Execution interrupted by steering signal: {reason}")]
    Interrupted {
        /// Reason for the interruption.
        reason: String,
    },
}

/// Errors occurring within the sandbox boundary or security matrix.
#[derive(Debug, Error, PartialEq, Eq)]
pub enum SandboxError {
    /// Path escapes the canonical root directory.
    #[error("Path traversal detected: {path}")]
    PathTraversalDetected {
        /// Path that violated confinement.
        path: String,
    },

    /// Attempt to access or modify a strictly protected resource (.env, .pem, credentials).
    #[error("Access to protected resource '{path}' is blocked: {reason}")]
    ProtectedResourceAccess {
        /// File path or resource targeted.
        path: String,
        /// Rationale for blocking access.
        reason: String,
    },

    /// Requested action is blocked by the permission matrix.
    #[error("Permission denied for operation '{operation}' on resource '{resource}'")]
    PermissionDenied {
        /// Operation attempted (e.g. read, write, exec).
        operation: String,
        /// Resource targeted.
        resource: String,
    },

    /// Resource consumption quota was exceeded by an external process.
    #[error("Resource quota exceeded for '{resource}': exceeded limit of {limit}")]
    QuotaExceeded {
        /// Resource that exceeded quota (e.g. "memory", "cpu", "time").
        resource: String,
        /// Description of the limit.
        limit: String,
    },

    /// A child subprocess failed to spawn or terminate cleanly.
    #[error("Subprocess execution failed for command '{command}': {reason}")]
    SubprocessFailed {
        /// Command that failed.
        command: String,
        /// Reason for failure.
        reason: String,
    },
}

/// Errors occurring during model inference or provider communication.
#[derive(Debug, Error, PartialEq, Eq)]
pub enum InferenceError {
    /// The inference endpoint rate-limited the request.
    #[error("Inference rate limit exceeded: retry after {retry_after_secs:?} seconds")]
    RateLimited {
        /// Estimated cooldown duration in seconds, if provided by endpoint.
        retry_after_secs: Option<u64>,
    },

    /// Network or connection failure communicating with the inference provider.
    #[error("Connection failure with provider '{provider}': {reason}")]
    ConnectionFailed {
        /// Identifier of the model provider endpoint.
        provider: String,
        /// Reason for connection failure.
        reason: String,
    },

    /// Model endpoint returned an unexpected error status.
    #[error("Provider '{provider}' returned error status {status_code}: {message}")]
    ProviderError {
        /// Provider name.
        provider: String,
        /// HTTP status code or provider error code.
        status_code: u16,
        /// Error description.
        message: String,
    },

    /// Context window limit of the model was exceeded.
    #[error("Context window exceeded on model '{model}': prompt tokens {prompt_tokens} > limit {context_limit}")]
    ContextWindowExceeded {
        /// Model identifier.
        model: String,
        /// Number of prompt tokens submitted.
        prompt_tokens: usize,
        /// Maximum allowed tokens for the model.
        context_limit: usize,
    },

    /// The requested model is not found or is unavailable.
    #[error("Model '{model}' is unavailable on provider '{provider}'")]
    ModelUnavailable {
        /// Provider name.
        provider: String,
        /// Model identifier.
        model: String,
    },
}

/// Errors occurring during configuration loading or parameter validation.
#[derive(Debug, Error, PartialEq, Eq)]
pub enum ConfigError {
    /// A mandatory configuration parameter is absent.
    #[error("Missing required configuration field: {field}")]
    MissingField {
        /// Name of the missing field.
        field: String,
    },

    /// A configuration value failed validation.
    #[error("Invalid configuration value for '{field}': {reason}")]
    InvalidValue {
        /// Name of the field.
        field: String,
        /// Reason explaining why the value is invalid.
        reason: String,
    },
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::error::Error;
    use std::io;

    #[test]
    fn test_internal_error_causal_chain() {
        let root_io_error =
            io::Error::new(io::ErrorKind::PermissionDenied, "access denied to port");
        let internal = InternalError::with_cause("Network socket bind failure", root_io_error);
        let kai_error: KaiError = internal.into();

        assert_eq!(
            kai_error.to_string(),
            "Internal runtime error: Network socket bind failure"
        );

        let source = kai_error.source().expect("source cause must be present");
        assert_eq!(source.to_string(), "access denied to port");
    }

    #[test]
    fn test_error_conversions() {
        let tool_err = ToolError::NotFound {
            name: "grep".to_string(),
        };
        let kai_tool: KaiError = tool_err.into();
        assert!(matches!(
            kai_tool,
            KaiError::Tool(ToolError::NotFound { .. })
        ));

        let sandbox_err = SandboxError::ProtectedResourceAccess {
            path: ".env".to_string(),
            reason: "Secrets cannot be accessed".to_string(),
        };
        let kai_sandbox: KaiError = sandbox_err.into();
        assert!(matches!(
            kai_sandbox,
            KaiError::Sandbox(SandboxError::ProtectedResourceAccess { .. })
        ));

        let inference_err = InferenceError::RateLimited {
            retry_after_secs: Some(30),
        };
        let kai_inf: KaiError = inference_err.into();
        assert!(matches!(
            kai_inf,
            KaiError::Inference(InferenceError::RateLimited { .. })
        ));

        let config_err = ConfigError::MissingField {
            field: "api_key".to_string(),
        };
        let kai_cfg: KaiError = config_err.into();
        assert!(matches!(
            kai_cfg,
            KaiError::Config(ConfigError::MissingField { .. })
        ));

        let from_str: KaiError = "fatal abort".into();
        assert!(matches!(from_str, KaiError::Internal(_)));
        assert_eq!(from_str.to_string(), "Internal runtime error: fatal abort");
    }

    #[test]
    fn test_error_display_formatting() {
        let err = SandboxError::QuotaExceeded {
            resource: "RAM".to_string(),
            limit: "50 MB".to_string(),
        };
        assert_eq!(
            err.to_string(),
            "Resource quota exceeded for 'RAM': exceeded limit of 50 MB"
        );
    }
}
